---
- name: Validate Firewall ACL's
  hosts: localhost
  gather_facts: no

  vars:
    snapshot_path: "../data/snapshots/snapshot"
    snapshot_name: "dual_tier_fw_snapshot"
    network_name: "dual_tier_fw_network"
    bf_service: 172.29.236.139

  roles:
    - batfish.base

  tasks:

  - name: Setup BF Session
    bf_session:
      host: "{{ bf_service }}"
      name: batfish_endpoint

  - name: Initialize BF Snapshot
    bf_init_snapshot:
      network: "{{ network_name }}"
      snapshot: "{{ snapshot_name }}"
      snapshot_data: "{{ snapshot_path }}"
      overwrite: true

  - name: Validate Flows
    bf_assert:
      assertions:
        - type: assert_filter_has_no_unreachable_lines
          name: Confirm that the FW1 XYZ ACL has no unreachable lines
          parameters:
            filters: 'FW1["acl-xyz"]'
      
        - type: assert_all_flows_succeed
          name: Confirm web server to db communication on MySQL tcp/3306 received on GigEth0/1 on FW1
          parameters:
            startLocation: '@enter(FW1[webfarm])'
            headers:
              srcIps: '10.0.1.1'
              dstIps: '10.0.2.1'
              dstPorts: '3306'
              ipProtocols: 'tcp'
    register: bf_assert
    ignore_errors: true

  - name: Display Batfish validation result details
    debug: msg="{{ bf_assert }}"


  - name: Validate ACLs                                                                                                               b
    bf_assert:  
      assertions:
        - type: assert_filter_has_no_unreachable_lines
          name: Confirm that the FW1 XYZ ACL has no unreachable lines
          parameters:
            filters: 'FW1["acl-xyz"]'

        - type: assert_all_flows_succeed
          name: Confirm web server to db communication on MySQL tcp/3306 received on GigEth0/1 on FW1
          parameters:
            startLocation: '@enter(FW1[webfarm])'
            headers:
              srcIps: '10.0.1.1'
              dstIps: '10.0.2.1'
              dstPorts: '3306'
              ipProtocols: 'tcp'
    register: bf_assert
    ignore_errors: true

  - name: Display Batfish validation result details
    debug: msg="{{ bf_assert }}"  
      assertions:
        - type: assert_filter_has_no_unreachable_lines
          name: Confirm that the FW1 XYZ ACL has no unreachable lines
          parameters:
            filters: 'FW1["acl-xyz"]'

        - type: assert_all_flows_succeed
          name: Confirm web server to db communication on MySQL tcp/3306 received on GigEth0/1 on FW1
          parameters:
            startLocation: '@enter(FW1[webfarm])'
            headers:
              srcIps: '10.0.1.1'
              dstIps: '10.0.2.1'
              dstPorts: '3306'
              ipProtocols: 'tcp'
    register: bf_assert
    ignore_errors: true

  - name: Display Batfish validation result details
    debug: msg="{{ bf_assert }}"

