---
- name: Initialize Network and Snapshot
  hosts: localhost
  gather_facts: no
  roles:
    - batfish.base

  tasks:

  - name: Setup BF Session
    bf_session:
      host: 172.29.236.139
      name: batfish_endpoint

  - name: Initialize BF Snapshot
    bf_init_snapshot:
      network: dual_tier_fw_network
      snapshot: dual_tier_fw_snapshot
      snapshot_data: ../data/snapshots/snapshot
      overwrite: true

  - name: Retrieve BF Facts
    bf_extract_facts:
      output_directory: ../data/bf_facts
