---
- name: Create Batfish Snapshot Directory
  hosts: localhost
  gather_facts: no
  
  vars:
    snapshot_dir: "../data/snapshots"
    snapshot_id: "snapshot-{{ lookup('pipe', 'date +%Y%m%d')}}"    
 
  tasks:
    - name: Create Snapshot Directory /
      file:
        path: "{{ snapshot_dir }}/{{ snapshot_id }}" 
        state: directory
    
    - name: Create Snapshot Directory /configs
      file:
        path: "{{ snapshot_dir }}/{{ snapshot_id }}/configs"
        state: directory

    - name: Create Snapshot Directory /hosts
      file:
        path: "{{ snapshot_dir }}/{{ snapshot_id }}/hosts"
        state: directory

    - name: Create Snapshot Directory /iptables
      file:
        path: "{{ snapshot_dir }}/{{ snapshot_id }}/iptables"
        state: directory

- name: Create Batfish Snapshot
  hosts: all
  gather_facts: yes

  vars:
    snapshot_dir: "./data/snapshots"
    template_dir: "./data/templates"
    snapshot_id: "snapshot-{{ lookup('pipe', 'date +%Y%m%d')}}"

  tasks:
    - name: Gather Device Configs
      asa_command:
        commands:
          - show running-config
      when: inventory_hostname in groups['asa']
      register: config

    - name: Save Device Configs to Snapshot
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "{{ snapshot_dir }}/{{ snapshot_id }}/configs/{{ inventory_hostname }}.cfg"
      when: inventory_hostname in groups['asa']

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      when: inventory_hostname in groups['linux']
 
    - name: find interface facts
      debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_%s' | format(item)]['ipv4'] }}"
      with_items: "{{ ansible_interfaces }}" 
      when: inventory_hostname in groups['linux']

    - name: Create host file 
      template:
        src: "../{{ template_dir }}/hosts.j2"
        dest: "../{{ snapshot_dir }}/{{ snapshot_id }}/hosts/{{ inventory_hostname }}.json"
      when: inventory_hostname in groups['linux']
