---
- name: Welcome to the first Batfish Tutorial!
  hosts: all
  gather_facts: no
  roles:
    - batfish.base

  tasks:

  - name: Execute Batfish related tasks in a block that is "delegate_to -> localhost" and "run_once -> true"
    block:

    - name: Setup connection to Batfish service
      bf_session:
        host: 172.29.236.139:8888
        name: batfish_endpoint
        parameters:
          ssl: true

    - name: Initialize the example network
      bf_init_snapshot:
        network: example_network
        snapshot: example_snapshot
        snapshot_data: ../data/snapshots/snapshot
        overwrite: true

    - name: Retrieve Batfish Facts
      bf_extract_facts:
        output_directory: data/bf_facts
      register: bf_facts

    - name: Display select facts gathered by Batfish
      block:

      - name: Display Batfish Facts for as1border1
        debug: msg="{{bf_facts.result}}"

    delegate_to: localhost
    run_once: true
