---
- name: Apply Configuration to NetDevices
  hosts: netdev
  gather_facts: no

  vars:
    snapshot_path: "./data/snapshots"
    snapshot_dir: "snapshot"

  tasks:
    - name: Remove Cryptochecksum Line
      lineinfile:
        path: '{{ snapshot_path }}/{{ snapshot_dir }}/configs/{{ inventory_hostname }}.cfg'
        state: absent
        regexp: 'Cryptocheck.*'
      when: inventory_hostname in groups['asa']
      delegate_to: localhost

    - name: Upload Configuration to Device
      expect:
        command: scp -o "StrictHostKeyChecking no" '{{ snapshot_path }}/{{ snapshot_dir }}/configs/{{ inventory_hostname }}.cfg' "{{ ansible_user }}"@"{{ hostvars[inventory_hostname]['ansible_host'] }}":"disk0:configuration.txt"
        responses:
          'password:': "{{ ansible_password }}"
        timeout: 180
      when: inventory_hostname in groups['asa']
     
    - name: Copy Configuration to Running Configuration
      asa_command:
        before: "clear configure access-list"
        commands:
          - "copy /noconfirm disk0:/configuration.txt running-config"
      ignore_errors: true
      when: inventory_hostname in groups['asa']
